services:
  db:
    image: mysql:8.4
    container_name: sir_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sir_db
      MYSQL_USER: sir_user
      MYSQL_PASSWORD: SIRmysql_2025!Q8
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--sql-mode=STRICT_TRANS_TABLES"
    ]

  backend:
    build:
      context: ./backend_django
      dockerfile: Dockerfile
    container_name: sir_backend
    env_file:
      - ./backend_django/.env
    environment:
      DB_ENGINE: mysql
      DB_NAME: sir_db
      DB_USER: sir_user
      DB_PASSWORD: SIRmysql_2025!Q8
      DB_HOST: db
      DB_PORT: 3306
      ALLOWED_HOSTS: backend,localhost,127.0.0.1,frontend
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000,http://frontend:3000
      CSRF_TRUSTED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000,http://frontend:3000
      MP_USE_SANDBOX: "true"
    ports:
      - "8002:8000"
    command: >
      bash -c "
        python scripts/wait_for_db.py &&
        python manage.py migrate &&
        python manage.py loaddata fixtures/auth_seed.json fixtures/reservas_seed.json &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend_django:/app:Z
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend_next
      dockerfile: Dockerfile
    container_name: sir_frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE: http://backend:8000
    ports:
      - "3001:3000"
    command: ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
    volumes:
      - ./frontend_next:/app:Z
      - /app/node_modules
    restart: unless-stopped

volumes:
  db_data:
