version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: sir_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sir_db
      MYSQL_USER: sir_user
      MYSQL_PASSWORD: SIRmysql_2025!Q8
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--sql-mode=STRICT_TRANS_TABLES",
      "--skip-host-cache",
      "--skip-name-resolve"
    ]

  backend:
    build:
      context: ./backend_django
      dockerfile: Dockerfile
    container_name: sir_backend
    depends_on:
      - db
    env_file:
      - ./backend_django/.env
    environment:
      DB_ENGINE: mysql
      DB_NAME: sir_db
      DB_USER: sir_user
      DB_PASSWORD: SIRmysql_2025!Q8
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "8000:8000"
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py loaddata fixtures/auth_seed.json fixtures/reservas_seed.json &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend_django:/app

  frontend:
    build:
      context: ./frontend_next
      dockerfile: Dockerfile
    container_name: sir_frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE: http://backend:8000
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
    volumes:
      - ./frontend_next:/app
      - /app/node_modules

volumes:
  db_data:
